services:
  - type: web
    name: threespacshine-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://haywood123.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
