services:
  - type: web
    name: threespacshine-api
    env: node
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
      - key: ADMIN_EMAIL
        value: haywoodlatrice4@gmail.com
      - key: ADMIN_PASSWORD
        value: Admin123!
      - key: CLIENT_URL
        value: https://threespacshine-production.netlify.app
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_Qab2v0WTBXue@ep-lucky-king-ae48anz8-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require
      - key: BUSINESS_NAME
        value: Three Space Shine
      - key: BUSINESS_EMAIL
        value: info@threespacshine.com
      - key: BUSINESS_ADDRESS
        value: Indianapolis, Indiana
